FROM node:10.14.2-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash ca-certificates git openssh openssl

WORKDIR /usr/src/app

ARG IO_PAGOPA_NODO_MOCK_COMMIT_SHA
ARG GITHUB_TOKEN
ARG PAGOPA_PORT
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

RUN rm -rf * && \
    git clone https://github.com/pagopa/io-pagopa-node-mock.git /usr/src/app && \
    git checkout PAG-605-original-fault-code 

RUN yarn install && \
    yarn build

EXPOSE ${PAGOPA_PORT}

CMD ["yarn", "start"]