parameters:
  # Required
  - name: "ENV_FILE"
    type: string

steps:
  - script: |
      yarn global add newman
    displayName: 'Newman installation'

  - script: |
      newman run api-tests/checkout-tests/checkout-for-ecommerce-api.tests.json -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/api-TEST.xml
    displayName: 'Run api test app - env file: ${{ parameters.ENV_FILE }}'
    continueOnError: true
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - script: |
      newman run api-tests/cart-tests/cart-api-dev.tests.json -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/api-TEST.xml
    displayName: 'Run api test api cart test - DEV'
    continueOnError: true
    condition: eq(contains('${{parameters.ENV_FILE}}', 'dev'), True)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - script: |
      newman run api-tests/cart-tests/cart-api-uat.tests.json -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/api-TEST.xml
    displayName: 'Run api test api cart test - UAT'
    continueOnError: true
    condition: eq(contains('${{parameters.ENV_FILE}}', 'uat'), True)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'