parameters:
  # Required
  - name: "CHECKOUT_FOR_ECOMMERCE_COLLECTION"
    type: "string"
  - name: "ENV_FILE"
    type: string
  - name: "TEST_FILE_PREFIX"
    type: string

steps:
  - script: |
      yarn global add newman
    displayName: 'Newman installation'

  - script: |
      newman run ${{ parameters.CHECKOUT_FOR_ECOMMERCE_COLLECTION }} -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/checkout-for-ecommerce-${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml
    displayName: 'Run api test app - env file: ${{ parameters.ENV_FILE }}'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - script: |
      newman run api-tests/cart-tests/cart-api-dev.tests.json -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/cart-api-dev-tests-TEST.xml
    displayName: 'Run api test api cart test - DEV'
    condition: eq(contains('${{parameters.ENV_FILE}}', 'dev'), True)
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'

  - script: |
      newman run api-tests/cart-tests/cart-api-uat.tests.json -e ${{ parameters.ENV_FILE }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/cart-api-${{ parameters.TEST_FILE_PREFIX }}-tests-TEST.xml
    displayName: 'Run api test api cart test - UAT'
    condition: eq(contains('${{parameters.ENV_FILE}}', 'uat'), True)
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'