apiVersion: v2
name: pagopa-ecommerce-payment-requests-service
description: Microservice that handles payment requests in ecommerce pagoPA
type: application
version: 1.4.1
appVersion: 1.4.1
dependencies:
  - name: microservice-chart
    version: 2.3.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
