microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: true
      headerName: deployment
      headerValue: blue
      weightPercent: 10
    image:
      repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentrequestsservice
      tag: "latest"
    envConfig:
      ECS_SERVICE_NAME: pagopa-ecommerce-payment-requests-service-blue
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-requests-service-blue,deployment.environment=prod"
    envSecret: {}
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentrequestsservice
    tag: "1.6.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 40
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 40
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 5
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-payment-requests-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  autoscaling:
    enable: true
    minReplica: 5
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  envConfig:
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    CHECKOUT_URL: https://api.platform.pagopa.it/ecommerce/checkout/v1/carts/{0}/redirect?clientId={1}
    NODO_HOSTNAME: https://api.platform.pagopa.it
    NODE_FOR_PSP_URI: /nodo/node-for-psp/v1
    NODO_PER_PM_URI: /nodo/nodo-per-pm/v1/checkPosition
    NODO_READ_TIMEOUT: "10000"
    NODO_CONNECTION_TIMEOUT: "10000"
    CARTS_MAX_ALLOWED_PAYMENT_NOTICES: "5"
    ECS_SERVICE_NAME: pagopa-ecommerce-payment-requests-service
    ECS_SERVICE_ENVIRONMENT: "prod"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-requests-service,deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
  envSecret:
    REDIS_PASSWORD: redis-ecommerce-access-key
    REDIS_HOST: redis-ecommerce-hostname
    NODO_CONNECTION_STRING: nodo-connection-string
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopaecommercepaymentrequestsservice
            namespaces: ["ecommerce"]
            topologyKey: topology.kubernetes.io/zone
  azure:
    workloadIdentityClientId: "d5614882-90dd-47a1-aad1-cdf295201469"
