microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: "beta-pagopa-ecommerce-payment-requests-service"
  canaryDelivery:
    create: false
    ingress:
      bluegreen: false
      #set canary deployment with traffic balancing see https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#canary for more info
      header: false
      headerName: deployment
      headerValue: blue
      weightPercent: 0
    image:
      repository: pagopaucommonacr.azurecr.io/pagopaecommercepaymentrequestsservice
      tag: "latest"
    envConfig:
      OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-requests-service-blue,deployment.environment=uat"
      ECS_SERVICE_NAME: pagopa-ecommerce-payment-requests-service-blue
      NODE_FOR_PSP_URI: /ecommerce/mock/nodo/v1
      NODO_PER_PM_URI: /ecommerce/mock/nodoPerPM/v1/checkPosition
      PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.uat.platform.pagopa.it/ecommerce/mock/pdv/v1"
      SECURITY_API_KEY_SECURED_PATHS: ""
    envSecret: {}
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaecommercepaymentrequestsservice
    tag: "3.1.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 3
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.ecommerce.internal.uat.platform.pagopa.it"
    path: /beta-pagopa-ecommerce-payment-requests-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "128Mi"
      cpu: "150m"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 5
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "80"
  terminationGracePeriodSeconds: 30
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  envConfig:
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    CHECKOUT_URL: https://api.uat.platform.pagopa.it/ecommerce/checkout/v1/carts/{0}/redirect?clientId={1}
    NODO_HOSTNAME: https://api.uat.platform.pagopa.it
    NODO_READ_TIMEOUT: "10000"
    NODO_CONNECTION_TIMEOUT: "10000"
    NODO_CONNECTION_STRING: "{\"idPSP\":\"AGID_01\",\"idChannel\":\"97735020584_09\",\"idBrokerPSP\":\"97735020584\"}"
    CARTS_MAX_ALLOWED_PAYMENT_NOTICES: "5"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECS_SERVICE_ENVIRONMENT: "uat"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.uat.platform.pagopa.it/ecommerce/mock/pdv/v1"
    SECURITY_API_KEY_SECURED_PATHS: ""
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-requests-service-blue,deployment.environment=uat"
    ECS_SERVICE_NAME: pagopa-ecommerce-payment-requests-service-blue
    NODE_FOR_PSP_URI: /ecommerce/mock/nodo/v1/verifyPaymentNotice
    NODO_PER_PM_URI: /ecommerce/mock/nodoPerPM/v1/checkPosition
  envSecret:
    REDIS_PASSWORD: redis-ecommerce-access-key
    REDIS_HOST: redis-ecommerce-hostname
    NODO_NODEFORECOMMERCE_API_KEY: node-for-ecommerce-api-v1-key
    NODO_NODEFORPSP_API_KEY: nodo-nodeforpsp-api-key
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
    SECURITY_API_KEY_PRIMARY: ecommerce-payment-requests-primary-api-key
    SECURITY_API_KEY_SECONDARY: ecommerce-payment-requests-secondary-api-key
  keyvault:
    name: "pagopa-u-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  azure:
    workloadIdentityClientId: 449c5b65-f368-487a-881a-b03676420c53
