oa3_spec: ./api-spec/api.yaml # If start with http the file would be downloaded from the internet
name: opex_pagopa-ecommerce-payment-requests-service
location: West Europe
timespan: 5m # Default, a number or a timespan https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan
data_source: /subscriptions/26abc801-0d8f-4a6e-ac5f-8e81bcc09112/resourceGroups/pagopa-u-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-u-app-gw
#data_source: /subscriptions/b9fc9419-6097-45fe-9f74-ba0641c91912/resourceGroups/pagopa-p-api-rg/providers/Microsoft.ApiManagement/service/pagopa-p-apim
resource_type: app-gateway
action_groups:
overrides:
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.uat.platform.pagopa.it
