name: Check PR

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, labeled, unlabeled, reopened, edited ]


permissions:
  pull-requests: write

jobs:
  check_labels:
    name: Check Required Labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - uses: ./.github/actions/check-pr-semver-labels
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  check_size:
    runs-on: ubuntu-latest
    name: Check Size
    steps:

      - name: Check PR Size
        uses: pagopa/github-actions-template/check-pr-size@3fae741d94bcb9873f2447e95cc4ddea6f77be4d
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignored_files: 'src/test/'
